import type { BusinessCategory } from "./types";

/** 생활언어 기반 업종 카테고리 */
export const businessCategories: BusinessCategory[] = [
  {
    id: "food",
    label: "음식점/카페",
    icon: "🍽️",
    subItems: [
      { id: "food-coffee", label: "커피음료" },
      { id: "food-dessert", label: "디저트" },
      { id: "food-restaurant", label: "음식점업" },
      { id: "food-cafe", label: "카페업" },
      { id: "food-takeout", label: "테이크아웃 서비스" },
      { id: "food-bakery", label: "베이커리" },
      { id: "food-delivery", label: "배달 서비스" },
      { id: "food-tea", label: "차/티 전문점" },
      { id: "food-juice", label: "주스/스무디" },
      { id: "food-icecream", label: "아이스크림/젤라토" },
      { id: "food-snack", label: "분식/간식" },
      { id: "food-meat", label: "정육/고기 전문점" },
      { id: "food-seafood", label: "수산물/해산물" },
      { id: "food-sauce", label: "소스/양념/조미료" },
      { id: "food-frozen", label: "냉동식품" },
      { id: "food-catering", label: "케이터링/출장뷔페" },
      { id: "food-franchise", label: "프랜차이즈 운영" },
      { id: "food-vegan", label: "비건/채식 식품" },
    ],
  },
  {
    id: "shopping",
    label: "온라인 쇼핑몰",
    icon: "🛒",
    subItems: [
      { id: "shop-retail", label: "온라인 소매업" },
      { id: "shop-platform", label: "오픈마켓/쇼핑 플랫폼" },
      { id: "shop-wholesale", label: "도매업" },
      { id: "shop-subscription", label: "구독 서비스" },
      { id: "shop-secondhand", label: "중고거래 플랫폼" },
      { id: "shop-groupbuy", label: "공동구매/소셜커머스" },
      { id: "shop-livecommerce", label: "라이브커머스" },
      { id: "shop-dropship", label: "위탁판매/드롭쉬핑" },
      { id: "shop-import", label: "수입대행/해외직구" },
      { id: "shop-gift", label: "선물/기프트 서비스" },
      { id: "shop-rental", label: "렌탈/대여 서비스" },
      { id: "shop-auction", label: "경매/입찰 서비스" },
      { id: "shop-comparison", label: "가격비교 서비스" },
      { id: "shop-membership", label: "멤버십/회원제 쇼핑" },
    ],
  },
  {
    id: "cosmetics",
    label: "화장품",
    icon: "💄",
    subItems: [
      { id: "cos-cosmetics", label: "화장품" },
      { id: "cos-skincare", label: "스킨케어 제품" },
      { id: "cos-perfume", label: "향수" },
      { id: "cos-retail", label: "화장품 소매업" },
      { id: "cos-online", label: "온라인 화장품 판매업" },
      { id: "cos-makeup", label: "색조 화장품" },
      { id: "cos-suncare", label: "자외선 차단제" },
      { id: "cos-hair", label: "헤어케어 제품" },
      { id: "cos-bodycare", label: "바디케어/바디워시" },
      { id: "cos-nail", label: "네일 제품" },
      { id: "cos-mask", label: "마스크팩/시트팩" },
      { id: "cos-men", label: "남성 화장품" },
      { id: "cos-baby", label: "유아/아동 화장품" },
      { id: "cos-organic", label: "자연/유기농 화장품" },
      { id: "cos-tools", label: "뷰티 도구/기기" },
      { id: "cos-salon", label: "미용실/헤어살롱" },
    ],
  },
  {
    id: "fashion",
    label: "의류/패션",
    icon: "👗",
    subItems: [
      { id: "fash-clothing", label: "의류" },
      { id: "fash-shoes", label: "신발" },
      { id: "fash-bags", label: "가방/잡화" },
      { id: "fash-accessories", label: "패션 액세서리" },
      { id: "fash-textiles", label: "직물/원단" },
      { id: "fash-retail", label: "의류 소매업" },
      { id: "fash-sportswear", label: "스포츠웨어/애슬레저" },
      { id: "fash-underwear", label: "속옷/이너웨어" },
      { id: "fash-kids", label: "아동복" },
      { id: "fash-luxury", label: "명품/럭셔리" },
      { id: "fash-jewelry", label: "주얼리/보석" },
      { id: "fash-hat", label: "모자/헤드웨어" },
      { id: "fash-eyewear", label: "안경/선글라스" },
      { id: "fash-uniform", label: "유니폼/단체복" },
      { id: "fash-secondhand", label: "빈티지/중고 패션" },
      { id: "fash-custom", label: "맞춤 제작/수선" },
    ],
  },
  {
    id: "health",
    label: "건강기능식품",
    icon: "💊",
    subItems: [
      { id: "health-supplement", label: "건강기능식품" },
      { id: "health-vitamin", label: "비타민/영양제" },
      { id: "health-diet", label: "다이어트 식품" },
      { id: "health-organic", label: "유기농 식품" },
      { id: "health-retail", label: "건강식품 소매업" },
      { id: "health-protein", label: "프로틴/운동 보충제" },
      { id: "health-probiotics", label: "유산균/프로바이오틱스" },
      { id: "health-herbal", label: "한방/약초 건강식품" },
      { id: "health-collagen", label: "콜라겐/이너뷰티" },
      { id: "health-kids", label: "어린이 건강식품" },
      { id: "health-senior", label: "시니어 건강식품" },
      { id: "health-functional", label: "기능성 음료" },
      { id: "health-powder", label: "분말/환/즙 제품" },
      { id: "health-detox", label: "디톡스/클렌즈" },
    ],
  },
  {
    id: "education",
    label: "교육/학원",
    icon: "📚",
    subItems: [
      { id: "edu-academy", label: "학원업" },
      { id: "edu-online", label: "온라인 교육 서비스" },
      { id: "edu-tutoring", label: "과외/튜터링" },
      { id: "edu-contents", label: "교육 콘텐츠 제작" },
      { id: "edu-consulting", label: "교육 컨설팅" },
      { id: "edu-language", label: "어학원/외국어 교육" },
      { id: "edu-coding", label: "코딩/IT 교육" },
      { id: "edu-art", label: "미술/음악/예체능 교육" },
      { id: "edu-exam", label: "입시/시험 대비 교육" },
      { id: "edu-certificate", label: "자격증/직업 교육" },
      { id: "edu-kindergarten", label: "유치원/어린이집" },
      { id: "edu-study", label: "스터디카페/독서실" },
      { id: "edu-book", label: "교재/학습 교구" },
      { id: "edu-camp", label: "캠프/체험학습" },
      { id: "edu-corporate", label: "기업 교육/연수" },
    ],
  },
  {
    id: "software",
    label: "소프트웨어/앱",
    icon: "💻",
    subItems: [
      { id: "sw-app", label: "다운로드 가능한 모바일 앱" },
      { id: "sw-saas", label: "SaaS" },
      { id: "sw-platform", label: "온라인 플랫폼 제공" },
      { id: "sw-data", label: "데이터 분석 서비스" },
      { id: "sw-dev", label: "소프트웨어 개발업" },
      { id: "sw-ai", label: "AI/인공지능 서비스" },
      { id: "sw-security", label: "보안/사이버보안" },
      { id: "sw-cloud", label: "클라우드/호스팅" },
      { id: "sw-erp", label: "ERP/업무관리 솔루션" },
      { id: "sw-fintech", label: "핀테크/결제 서비스" },
      { id: "sw-iot", label: "IoT/스마트기기" },
      { id: "sw-blockchain", label: "블록체인/NFT" },
      { id: "sw-game", label: "게임 개발/퍼블리싱" },
      { id: "sw-edtech", label: "에듀테크" },
      { id: "sw-healthtech", label: "헬스테크/디지털 헬스" },
    ],
  },
  {
    id: "medical",
    label: "병원/의원",
    icon: "🏥",
    subItems: [
      { id: "med-clinic", label: "의원/병원업" },
      { id: "med-dental", label: "치과" },
      { id: "med-derma", label: "피부과/미용의원" },
      { id: "med-pharmacy", label: "약국업" },
      { id: "med-device", label: "의료기기" },
      { id: "med-oriental", label: "한의원/한방" },
      { id: "med-eye", label: "안과/시력교정" },
      { id: "med-plastic", label: "성형외과" },
      { id: "med-mental", label: "정신건강/심리상담" },
      { id: "med-rehab", label: "재활/물리치료" },
      { id: "med-nursing", label: "간호/요양 서비스" },
      { id: "med-lab", label: "의료 검사/진단" },
      { id: "med-telemedicine", label: "원격진료/비대면 의료" },
      { id: "med-vet", label: "수의과/동물 의료" },
    ],
  },
  {
    id: "pet",
    label: "반려동물",
    icon: "🐾",
    subItems: [
      { id: "pet-food", label: "반려동물 사료/간식" },
      { id: "pet-supplies", label: "반려동물 용품" },
      { id: "pet-grooming", label: "반려동물 미용" },
      { id: "pet-hospital", label: "동물병원" },
      { id: "pet-hotel", label: "반려동물 호텔/돌봄" },
      { id: "pet-training", label: "반려동물 훈련/교육" },
      { id: "pet-clothing", label: "반려동물 의류/패션" },
      { id: "pet-health", label: "반려동물 건강식품" },
      { id: "pet-toy", label: "반려동물 장난감" },
      { id: "pet-funeral", label: "반려동물 장례/추모" },
      { id: "pet-insurance", label: "반려동물 보험" },
      { id: "pet-app", label: "반려동물 앱/플랫폼" },
      { id: "pet-cafe", label: "애견카페/동물카페" },
      { id: "pet-breeding", label: "브리딩/분양" },
    ],
  },
  {
    id: "consulting",
    label: "컨설팅/전문서비스",
    icon: "📋",
    subItems: [
      { id: "con-management", label: "경영 컨설팅" },
      { id: "con-legal", label: "법률 서비스" },
      { id: "con-accounting", label: "회계/세무" },
      { id: "con-marketing", label: "마케팅/광고 대행" },
      { id: "con-design", label: "디자인 서비스" },
      { id: "con-hr", label: "인사/채용 컨설팅" },
      { id: "con-it", label: "IT 컨설팅" },
      { id: "con-patent", label: "특허/지식재산 서비스" },
      { id: "con-realestate", label: "부동산 컨설팅" },
      { id: "con-finance", label: "금융/투자 자문" },
      { id: "con-startup", label: "창업/스타트업 컨설팅" },
      { id: "con-trade", label: "무역/수출입 컨설팅" },
      { id: "con-environment", label: "환경/ESG 컨설팅" },
      { id: "con-translation", label: "번역/통역 서비스" },
      { id: "con-research", label: "시장조사/리서치" },
    ],
  },
  {
    id: "furniture",
    label: "가구/인테리어",
    icon: "🛋️",
    subItems: [
      { id: "fur-furniture", label: "가구" },
      { id: "fur-lighting", label: "조명/인테리어 소품" },
      { id: "fur-carpet", label: "카펫/러그/매트" },
      { id: "fur-curtain", label: "커튼/블라인드" },
      { id: "fur-retail", label: "가구/인테리어 소매업" },
      { id: "fur-office", label: "사무용 가구" },
      { id: "fur-kitchen", label: "주방 가구/수납" },
      { id: "fur-bed", label: "침대/매트리스" },
      { id: "fur-kids", label: "유아/아동 가구" },
      { id: "fur-outdoor", label: "야외용 가구" },
      { id: "fur-wallpaper", label: "벽지/도배" },
      { id: "fur-flooring", label: "바닥재/타일" },
      { id: "fur-custom", label: "맞춤 가구 제작" },
      { id: "fur-antique", label: "앤틱/빈티지 가구" },
    ],
  },
  {
    id: "appliances",
    label: "가전/생활용품",
    icon: "🔌",
    subItems: [
      { id: "app-home", label: "가정용 가전제품" },
      { id: "app-kitchen", label: "주방용품/조리기구" },
      { id: "app-cleaning", label: "세정제/생활화학" },
      { id: "app-daily", label: "생활용품" },
      { id: "app-retail", label: "가전/생활용품 소매업" },
      { id: "app-aircon", label: "냉난방/공기청정기" },
      { id: "app-laundry", label: "세탁기/건조기" },
      { id: "app-vacuum", label: "청소기/로봇청소기" },
      { id: "app-water", label: "정수기/공기청정기" },
      { id: "app-smart", label: "스마트홈 기기" },
      { id: "app-bathroom", label: "욕실용품/위생용품" },
      { id: "app-storage", label: "수납/정리 용품" },
      { id: "app-stationery", label: "문구/사무용품" },
      { id: "app-candle", label: "캔들/디퓨저/방향제" },
    ],
  },
  {
    id: "sports",
    label: "스포츠/레저",
    icon: "⚽",
    subItems: [
      { id: "spt-equipment", label: "스포츠 용품" },
      { id: "spt-outdoor", label: "아웃도어/캠핑" },
      { id: "spt-toys", label: "장난감/완구" },
      { id: "spt-games", label: "게임/보드게임" },
      { id: "spt-gym", label: "체육관/피트니스" },
      { id: "spt-retail", label: "스포츠용품 소매업" },
      { id: "spt-golf", label: "골프 용품/골프장" },
      { id: "spt-swim", label: "수영/수상 스포츠" },
      { id: "spt-bike", label: "자전거/사이클링" },
      { id: "spt-yoga", label: "요가/필라테스" },
      { id: "spt-ski", label: "스키/보드/동계 스포츠" },
      { id: "spt-fishing", label: "낚시 용품" },
      { id: "spt-martial", label: "무술/격투기 도장" },
      { id: "spt-esports", label: "e스포츠/게이밍" },
      { id: "spt-travel", label: "여행/관광 서비스" },
      { id: "spt-theme", label: "테마파크/놀이공원" },
    ],
  },
  {
    id: "alcohol",
    label: "주류",
    icon: "🍷",
    subItems: [
      { id: "alc-wine", label: "와인" },
      { id: "alc-beer", label: "맥주/크래프트 비어" },
      { id: "alc-soju", label: "소주/전통주" },
      { id: "alc-spirits", label: "양주/증류주" },
      { id: "alc-bar", label: "바/주점 운영" },
      { id: "alc-retail", label: "주류 소매업" },
      { id: "alc-sake", label: "사케/일본주" },
      { id: "alc-makgeolli", label: "막걸리/탁주" },
      { id: "alc-cocktail", label: "칵테일/RTD 음료" },
      { id: "alc-brewery", label: "양조장/브루어리" },
      { id: "alc-winery", label: "와이너리/포도원" },
      { id: "alc-import", label: "수입주류 유통" },
      { id: "alc-snack", label: "안주/주류 푸드페어링" },
    ],
  },
  {
    id: "construction",
    label: "건설/시공",
    icon: "🏗️",
    subItems: [
      { id: "const-building", label: "건축/시공업" },
      { id: "const-interior", label: "인테리어 시공" },
      { id: "const-materials", label: "건축자재" },
      { id: "const-repair", label: "수리/보수업" },
      { id: "const-metal", label: "철물/금속자재" },
      { id: "const-electrical", label: "전기/전선 공사" },
      { id: "const-plumbing", label: "배관/설비 공사" },
      { id: "const-painting", label: "도장/도배 공사" },
      { id: "const-window", label: "창호/유리 시공" },
      { id: "const-roof", label: "지붕/방수 공사" },
      { id: "const-demolition", label: "철거/해체 공사" },
      { id: "const-landscape", label: "조경/정원 시공" },
      { id: "const-civil", label: "토목 공사" },
      { id: "const-safety", label: "안전 설비/소방" },
    ],
  },
  {
    id: "automobile",
    label: "자동차",
    icon: "🚗",
    subItems: [
      { id: "auto-vehicle", label: "자동차/차량" },
      { id: "auto-parts", label: "자동차 부품/용품" },
      { id: "auto-repair", label: "자동차 정비/수리" },
      { id: "auto-rental", label: "렌터카/리스" },
      { id: "auto-retail", label: "자동차용품 소매업" },
      { id: "auto-ev", label: "전기차/충전 인프라" },
      { id: "auto-wash", label: "세차/디테일링" },
      { id: "auto-insurance", label: "자동차 보험" },
      { id: "auto-used", label: "중고차 매매" },
      { id: "auto-tires", label: "타이어/휠" },
      { id: "auto-audio", label: "카오디오/전자장비" },
      { id: "auto-wrap", label: "래핑/튜닝" },
      { id: "auto-driving", label: "운전학원/교육" },
      { id: "auto-parking", label: "주차장/발렛" },
    ],
  },
  {
    id: "telecom",
    label: "통신/미디어",
    icon: "📡",
    subItems: [
      { id: "tel-telecom", label: "통신 서비스" },
      { id: "tel-broadcast", label: "방송/스트리밍" },
      { id: "tel-media", label: "미디어/콘텐츠 제작" },
      { id: "tel-internet", label: "인터넷 서비스" },
      { id: "tel-podcast", label: "팟캐스트/오디오" },
      { id: "tel-news", label: "뉴스/언론 미디어" },
      { id: "tel-sns", label: "SNS/소셜미디어" },
      { id: "tel-advertising", label: "디지털 광고" },
      { id: "tel-video", label: "영상 촬영/편집" },
      { id: "tel-webtoon", label: "웹툰/웹소설" },
      { id: "tel-publishing", label: "출판/전자출판" },
      { id: "tel-photo", label: "사진/포토 서비스" },
    ],
  },
  {
    id: "music",
    label: "음악/공연",
    icon: "🎵",
    subItems: [
      { id: "mus-instrument", label: "악기" },
      { id: "mus-production", label: "음반/음악 제작" },
      { id: "mus-performance", label: "공연/이벤트 기획" },
      { id: "mus-education", label: "음악 교육" },
      { id: "mus-retail", label: "악기/음반 소매업" },
      { id: "mus-studio", label: "녹음 스튜디오" },
      { id: "mus-streaming", label: "음원 스트리밍" },
      { id: "mus-dj", label: "DJ/사운드 서비스" },
      { id: "mus-karaoke", label: "노래방/코인노래방" },
      { id: "mus-ticket", label: "공연 티켓 예매" },
      { id: "mus-rental", label: "악기/음향 장비 대여" },
      { id: "mus-composition", label: "작곡/편곡 서비스" },
    ],
  },
  {
    id: "manufacturing",
    label: "제조업",
    icon: "🏭",
    subItems: [
      { id: "mfg-general", label: "일반 제조업" },
      { id: "mfg-chemical", label: "화학제품/원료" },
      { id: "mfg-paint", label: "도료/페인트/코팅" },
      { id: "mfg-rubber", label: "고무/플라스틱 제품" },
      { id: "mfg-tools", label: "공구/수공구" },
      { id: "mfg-energy", label: "연료/에너지" },
      { id: "mfg-electronics", label: "전자부품/반도체" },
      { id: "mfg-textile", label: "섬유/원사 제조" },
      { id: "mfg-paper", label: "종이/포장재" },
      { id: "mfg-food", label: "식품 가공/제조" },
      { id: "mfg-printing", label: "인쇄/출력 서비스" },
      { id: "mfg-metal", label: "금속 제품 제조" },
      { id: "mfg-glass", label: "유리/세라믹 제조" },
      { id: "mfg-oem", label: "OEM/ODM 위탁생산" },
    ],
  },
  {
    id: "logistics",
    label: "물류/운송",
    icon: "🚚",
    subItems: [
      { id: "other-logistics", label: "물류/운송" },
      { id: "log-courier", label: "택배/퀵서비스" },
      { id: "log-warehouse", label: "물류 창고/풀필먼트" },
      { id: "log-international", label: "국제 물류/포워딩" },
      { id: "log-moving", label: "이사/포장 서비스" },
      { id: "log-cold", label: "냉장/냉동 물류" },
      { id: "log-lastmile", label: "라스트마일 배송" },
      { id: "log-freight", label: "화물 운송" },
      { id: "log-customs", label: "통관/관세 대행" },
      { id: "log-storage", label: "보관/창고 대여" },
    ],
  },
  {
    id: "realestate",
    label: "부동산",
    icon: "🏠",
    subItems: [
      { id: "other-realestate", label: "부동산 중개" },
      { id: "re-management", label: "부동산 관리" },
      { id: "re-development", label: "부동산 개발" },
      { id: "re-lease", label: "임대/리스업" },
      { id: "re-appraisal", label: "감정평가" },
      { id: "re-commercial", label: "상업용 부동산" },
      { id: "re-officetel", label: "오피스텔/원룸" },
      { id: "re-coworking", label: "공유오피스/코워킹" },
      { id: "re-platform", label: "부동산 플랫폼" },
      { id: "re-interior", label: "인테리어 중개" },
    ],
  },
  {
    id: "entertainment",
    label: "엔터테인먼트",
    icon: "🎬",
    subItems: [
      { id: "other-entertainment", label: "연예/오락" },
      { id: "ent-film", label: "영화 제작/배급" },
      { id: "ent-drama", label: "드라마/시리즈 제작" },
      { id: "ent-animation", label: "애니메이션" },
      { id: "ent-talent", label: "연예 매니지먼트" },
      { id: "ent-fanplatform", label: "팬 플랫폼/커뮤니티" },
      { id: "ent-character", label: "캐릭터/IP 사업" },
      { id: "ent-vr", label: "VR/AR 콘텐츠" },
      { id: "ent-arcade", label: "오락실/게임센터" },
      { id: "ent-escape", label: "방탈출/체험형 놀이" },
      { id: "ent-party", label: "파티/이벤트 공간" },
    ],
  },
  {
    id: "other",
    label: "기타",
    icon: "📦",
    subItems: [
      { id: "other-etc", label: "기타" },
    ],
  },
];
